# Generated by Django 5.0.1 on 2025-05-17 07:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manpowerexpense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='manpowerexpense',
            name='manpower_id',
        ),
        migrations.RemoveField(
            model_name='materialexpense',
            name='material_id',
        ),
        migrations.AlterField(
            model_name='manpowerexpense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='materialexpense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='materialexpense',
            name='custom_item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materialexpense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialexpense',
            name='item',
            field=models.CharField(choices=[('brick', 'Brick'), ('cement', 'Cement'), ('steel', 'Steel'), ('sand', 'Sand'), ('aggregate', 'Jelly'), ('paint', 'Paint'), ('tiles', 'Tiles'), ('wood', 'Wood'), ('stone pebbles', 'Stone pebbles'), ('grinate', 'Grinate'), ('electrical', 'Electrical Items'), ('plumbing', 'Plumbing Items'), ('others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='materialexpense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
    ]
