# Generated by Django 5.0.1 on 2025-05-17 07:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_alter_manpowerexpense_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manpowerexpense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='materialexpense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
