# Generated by Django 5.0.1 on 2025-05-25 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_alter_manpowerexpense_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration_months',
            field=models.PositiveIntegerField(default=1, help_text='Project duration in months'),
        ),
        migrations.AlterField(
            model_name='materialexpense',
            name='total_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
