# Generated by Django 5.0.1 on 2025-05-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_project_duration_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
