# Generated by Django 4.2 on 2025-06-17 02:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_alter_project_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('construction', 'Construction work'), ('water_sanitary', 'Water and sanitary'), ('electric', 'Electric'), ('granite', 'Granite'), ('wood_work', 'Wood work'), ('grill_work', 'Grill work'), ('paint_work', 'Paint work'), ('earth_work', 'Earth work'), ('carpenter', 'Carpenter')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='manpowerexpense',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manpower_expenses', to='construction.laborworktype'),
        ),
    ]
