# Generated by Django 4.2 on 2025-06-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_add_material_items'),
        ('construction', '0007_add_work_type'),
    ]

    operations = [
    ]
