# Generated by Django 4.2 on 2025-06-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_create_material_items'),
        ('construction', '0009_create_material_items'),
    ]

    operations = [
    ]
